# Generated by Django 2.0.4 on 2018-04-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180421_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, null=True, verbose_name='Imię')),
                ('mobile', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefon')),
                ('message', models.TextField(max_length=124, verbose_name='Wiadomość')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
