# Generated by Django 2.0.4 on 2018-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='message',
        ),
        migrations.AddField(
            model_name='sms',
            name='body',
            field=models.IntegerField(choices=[(1, 'Mam nie typową propozycje. Proszę o kontakt.'), (2, 'Chcę unowocześnić moją firmę.'), (3, 'Ma pomysł na start-up.'), (4, 'Potrzebuję strony internetowej.'), (5, 'Chcę przeprzowadzić akcję promocyjną.'), (6, 'Potrzebuję kampanii marketingowej.'), (7, 'Chcę reaktywować moją listę mailingową.')], default=0, verbose_name='Wiadomość'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sms',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='Imię'),
        ),
    ]
