# Generated by Django 2.0.4 on 2018-04-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20180422_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
